#!/usr/bin/env bash
set -euo pipefail
mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" <<SQL
CREATE DATABASE IF NOT EXISTS commerce_operations;
CREATE DATABASE IF NOT EXISTS commerce_order_engine;
CREATE USER IF NOT EXISTS '${MYSQL_OPERATIONS_USER}'@'%' IDENTIFIED BY '${MYSQL_OPERATIONS_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_ORDER_USER}'@'%' IDENTIFIED BY '${MYSQL_ORDER_PASSWORD}';
GRANT ALL PRIVILEGES ON commerce_operations.* TO '${MYSQL_OPERATIONS_USER}'@'%';
GRANT ALL PRIVILEGES ON commerce_order_engine.* TO '${MYSQL_ORDER_USER}'@'%';
FLUSH PRIVILEGES;
SQL
