using Commerce.Operations.Api.Customers;using Commerce.Operations.Api.Products;using FluentValidation;
namespace Commerce.Operations.Api.Orders;
public static class OrderEndpoints{public static IEndpointRouteBuilder MapOrderEndpoints(this IEndpointRouteBuilder endpoints){var g=endpoints.MapGroup("/api/orders").RequireAuthorization().WithTags("Orders");
 g.MapGet("",async(int page,int pageSize,OrderGateway gateway)=>page<1||pageSize is <1 or >100?Results.ValidationProblem(new Dictionary<string,string[]>{{"pagination",["Invalid pagination."]}}):await Try(()=>gateway.ListAsync(page,pageSize)));
 g.MapGet("/{id:long}",async(long id,OrderGateway gateway)=>await Try(()=>gateway.GetAsync(id)));
 g.MapPost("",async(CreateOrderRequest request,IValidator<CreateOrderRequest> validator,CustomerRepository customers,ProductRepository products,OrderGateway gateway)=>{var v=await validator.ValidateAsync(request);if(!v.IsValid)return Results.ValidationProblem(v.ToDictionary());var customer=await customers.GetAsync(request.CustomerId);if(customer is null)return Results.NotFound(new{title="Customer not found"});if(customer.Status!=CustomerStatuses.Active)return Results.Conflict(new{title="Customer is not active"});var items=new List<EngineCreateOrderItem>();foreach(var item in request.Items){var product=await products.GetAsync(item.ProductId);if(product is null)return Results.NotFound(new{title=$"Product {item.ProductId} not found"});if(product.Status!=ProductStatuses.Active)return Results.Conflict(new{title=$"Product {item.ProductId} is not active"});items.Add(new(product.Id,product.Sku,product.Name,product.Price,item.Quantity));}try{return Results.Created("/api/orders",await gateway.CreateAsync(new(customer.Id,customer.Email,customer.Name,items)));}catch(OrderGatewayException e){return Error(e);}}).RequireAuthorization("AdminOnly");
 g.MapPost("/{id:long}/cancel",async(long id,OrderGateway gateway)=>await Try(()=>gateway.CancelAsync(id))).RequireAuthorization("AdminOnly");
 g.MapPost("/{id:long}/pay",async(long id,OrderGateway gateway)=>await Try(()=>gateway.PayAsync(id))).RequireAuthorization("AdminOnly");
 g.MapPost("/{id:long}/refund",async(long id,OrderGateway gateway)=>await Try(()=>gateway.RefundAsync(id))).RequireAuthorization("AdminOnly");
 g.MapPost("/{id:long}/ship",async(long id,ShipOrderRequest request,IValidator<ShipOrderRequest> validator,OrderGateway gateway)=>{var validation=await validator.ValidateAsync(request);return validation.IsValid?await Try(()=>gateway.ShipAsync(id,request)):Results.ValidationProblem(validation.ToDictionary());}).RequireAuthorization("AdminOnly");
 g.MapPost("/{id:long}/deliver",async(long id,OrderGateway gateway)=>await Try(()=>gateway.DeliverAsync(id))).RequireAuthorization("AdminOnly");return endpoints;}
 private static async Task<IResult> Try<T>(Func<Task<T>> action){try{return Results.Ok(await action());}catch(OrderGatewayException e){return Error(e);}}
 private static IResult Error(OrderGatewayException e)=>Results.Problem(statusCode:(int)e.StatusCode,title:"Order engine request failed",detail:e.Message.Length>500?e.Message[..500]:e.Message);
}
