import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Alert,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,InputLabel,MenuItem,Paper,Select,Table,TableBody,TableCell,TableContainer,TableHead,TablePagination,TableRow,TextField,Typography } from '@mui/material';
import axios from 'axios';import { useState } from 'react';
import { cancelOrder,createOrder,deliverOrder,getOrder,getOrders,payOrder,refundOrder,shipOrder,type OrderSummary,type OrderStatus } from '../api/orders';import { getCustomers } from '../api/customers';import { getProducts } from '../api/products';

export function OrdersPage(){const qc=useQueryClient();const[page,setPage]=useState(0);const[size,setSize]=useState(20);const[createOpen,setCreateOpen]=useState(false);const[selected,setSelected]=useState<OrderSummary|null>(null);
 const[shipOpen,setShipOpen]=useState(false);const[carrier,setCarrier]=useState('');const[tracking,setTracking]=useState('');
 const orders=useQuery({queryKey:['orders',page,size],queryFn:()=>getOrders(page+1,size)});const detail=useQuery({queryKey:['order',selected?.id],queryFn:()=>getOrder(selected!.id),enabled:!!selected});
 const cancel=useMutation({mutationFn:cancelOrder,onSuccess:()=>{void qc.invalidateQueries({queryKey:['orders']});void qc.invalidateQueries({queryKey:['inventories']});setSelected(null);}});
 const payment=useMutation({mutationFn:({id,refund}:{id:number;refund:boolean})=>refund?refundOrder(id):payOrder(id),onSuccess:(_,v)=>{void qc.invalidateQueries({queryKey:['orders']});void qc.invalidateQueries({queryKey:['order',v.id]});void qc.invalidateQueries({queryKey:['inventories']});}});
 const shipping=useMutation({mutationFn:({id,deliver}:{id:number;deliver:boolean})=>deliver?deliverOrder(id):shipOrder(id,carrier,tracking),onSuccess:(_,v)=>{setShipOpen(false);void qc.invalidateQueries({queryKey:['orders']});void qc.invalidateQueries({queryKey:['order',v.id]});void qc.invalidateQueries({queryKey:['inventories']});}});
 const statusLabel=(status:OrderStatus)=>({CREATED:'생성',PAID:'결제완료',SHIPPED:'배송중',COMPLETED:'배송완료',CANCELLED:'취소',REFUNDED:'환불완료'}[status]);
 return <Box><Box sx={{display:'flex',justifyContent:'space-between',mb:3}}><Box><Typography variant="h4">주문 관리</Typography><Typography color="text.secondary">주문 생성 시 재고가 예약되며 취소하면 예약이 해제됩니다.</Typography></Box><Button variant="contained" onClick={()=>setCreateOpen(true)}>주문 생성</Button></Box>
 {orders.isError&&<Alert severity="error">주문 목록을 불러오지 못했습니다.</Alert>}<TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>주문번호</TableCell><TableCell>회원</TableCell><TableCell>상태</TableCell><TableCell align="right">금액</TableCell><TableCell>생성시각</TableCell></TableRow></TableHead><TableBody>{orders.data?.items.map(o=><TableRow hover key={o.id} onClick={()=>setSelected(o)} sx={{cursor:'pointer'}}><TableCell>#{o.id}</TableCell><TableCell>{o.customerName}<br/><Typography variant="caption">{o.customerEmail}</Typography></TableCell><TableCell>{statusLabel(o.status)}</TableCell><TableCell align="right">{Number(o.totalAmount).toLocaleString()}원</TableCell><TableCell>{new Date(o.createdAt).toLocaleString()}</TableCell></TableRow>)}</TableBody></Table><TablePagination component="div" count={orders.data?.totalCount??0} page={page} rowsPerPage={size} onPageChange={(_,v)=>setPage(v)} onRowsPerPageChange={e=>{setPage(0);setSize(Number(e.target.value));}}/></TableContainer>
 <CreateOrderDialog open={createOpen} onClose={()=>setCreateOpen(false)} onCreated={()=>{setCreateOpen(false);void qc.invalidateQueries({queryKey:['orders']});void qc.invalidateQueries({queryKey:['inventories']});}}/>
 <Dialog open={!!selected} onClose={()=>setSelected(null)} maxWidth="md" fullWidth><DialogTitle>주문 #{selected?.id} · {detail.data&&statusLabel(detail.data.status)}</DialogTitle><DialogContent>{detail.isLoading?'불러오는 중…':<><Typography sx={{mb:2}}>{detail.data?.customerName} · {detail.data?.customerEmail}</Typography><Table size="small"><TableHead><TableRow><TableCell>상품</TableCell><TableCell align="right">단가</TableCell><TableCell align="right">수량</TableCell><TableCell align="right">금액</TableCell></TableRow></TableHead><TableBody>{detail.data?.items.map(i=><TableRow key={i.id}><TableCell>{i.sku} · {i.productName}</TableCell><TableCell align="right">{Number(i.unitPrice).toLocaleString()}</TableCell><TableCell align="right">{i.quantity}</TableCell><TableCell align="right">{Number(i.lineAmount).toLocaleString()}</TableCell></TableRow>)}</TableBody></Table>{(cancel.isError||payment.isError||shipping.isError)&&<Alert severity="error" sx={{mt:2}}>요청을 처리할 수 없습니다. 현재 주문 상태를 확인하세요.</Alert>}</>}</DialogContent><DialogActions><Button onClick={()=>setSelected(null)}>닫기</Button>{detail.data?.status==='CREATED'&&<Button color="error" disabled={cancel.isPending||payment.isPending} onClick={()=>cancel.mutate(detail.data!.id)}>주문 취소</Button>}{detail.data?.status==='CREATED'&&<Button variant="contained" disabled={payment.isPending} onClick={()=>payment.mutate({id:detail.data!.id,refund:false})}>결제 승인</Button>}{detail.data?.status==='PAID'&&<Button color="warning" disabled={payment.isPending} onClick={()=>payment.mutate({id:detail.data!.id,refund:true})}>환불</Button>}{detail.data?.status==='PAID'&&<Button variant="contained" onClick={()=>{setCarrier('');setTracking('');setShipOpen(true);}}>배송 시작</Button>}{detail.data?.status==='SHIPPED'&&<Button variant="contained" disabled={shipping.isPending} onClick={()=>shipping.mutate({id:detail.data!.id,deliver:true})}>배송 완료</Button>}</DialogActions></Dialog>
 <Dialog open={shipOpen} onClose={()=>setShipOpen(false)} fullWidth><DialogTitle>배송 정보 등록</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px !important'}}><TextField label="운송사" value={carrier} onChange={e=>setCarrier(e.target.value)}/><TextField label="송장번호" value={tracking} onChange={e=>setTracking(e.target.value)} helperText="영문, 숫자, 하이픈만 입력"/></DialogContent><DialogActions><Button onClick={()=>setShipOpen(false)}>취소</Button><Button variant="contained" disabled={!carrier.trim()||!/^[A-Za-z0-9-]+$/.test(tracking)||shipping.isPending} onClick={()=>shipping.mutate({id:detail.data!.id,deliver:false})}>등록</Button></DialogActions></Dialog>
 </Box>}

function CreateOrderDialog({open,onClose,onCreated}:{open:boolean;onClose:()=>void;onCreated:()=>void}){const[customerId,setCustomerId]=useState('');const[productId,setProductId]=useState('');const[quantity,setQuantity]=useState(1);const customers=useQuery({queryKey:['customers','order-options'],queryFn:()=>getCustomers({page:1,pageSize:100,status:'ACTIVE'}),enabled:open});const products=useQuery({queryKey:['products','order-options'],queryFn:()=>getProducts({page:1,pageSize:100,status:'ACTIVE'}),enabled:open});const create=useMutation({mutationFn:createOrder,onSuccess:onCreated});return <Dialog open={open} onClose={onClose} fullWidth><DialogTitle>주문 생성</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px !important'}}><FormControl><InputLabel>회원</InputLabel><Select value={customerId} label="회원" onChange={e=>setCustomerId(String(e.target.value))}>{customers.data?.items.map(c=><MenuItem key={c.id} value={String(c.id)}>{c.name} ({c.email})</MenuItem>)}</Select></FormControl><FormControl><InputLabel>상품</InputLabel><Select value={productId} label="상품" onChange={e=>setProductId(String(e.target.value))}>{products.data?.items.map(p=><MenuItem key={p.id} value={String(p.id)}>{p.sku} · {p.name} · {Number(p.price).toLocaleString()}원</MenuItem>)}</Select></FormControl><TextField label="수량" type="number" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} slotProps={{htmlInput:{min:1}}}/>{create.isError&&<Alert severity="error">{axios.isAxiosError(create.error)&&create.error.response?.status===409?'재고가 부족하거나 주문할 수 없습니다.':'주문 생성에 실패했습니다.'}</Alert>}</DialogContent><DialogActions><Button onClick={onClose}>취소</Button><Button variant="contained" disabled={!customerId||!productId||quantity<1||create.isPending} onClick={()=>create.mutate({customerId:Number(customerId),items:[{productId:Number(productId),quantity}]})}>생성</Button></DialogActions></Dialog>}
